name: Build Blazor Application

on:
  push:
    branches:
      - main
    paths:
      - 'src/Blazor/**/*'
      - '.github/workflows/main_build-blazor.yml' 

jobs:
  build_blazor:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '7.0.x'

    - name: Build Solution
      run: dotnet build Hybrid-StarterKit\HybridNativeApiSample\HybridNativeApiSample.csproj --no-restore --configuration Release
