name: Build Blazor Application

on:
  push:
    branches: [ master ]
    paths:
      - 'HybridNativeApiSample/**/*'
      - '.github/workflows/main.yml' 

jobs:
  build_blazor:
    runs-on: windows-2022
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '7.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore Dependencies
      run: dotnet restore HybridNativeApiSample/HybridNativeApiSample.csproj
      
    - name: Build Solution
      run: dotnet build HybridNativeApiSample/HybridNativeApiSample.csproj --no-restore --configuration Release
